name: Trigger auto deployment for croston-nodetestdeno-001

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/croston-nodetestdeno-001-AutoDeployTrigger-f863e9f6-6ce1-4dfd-aacb-8ed5be0478c0.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CROSTONNODETESTDENO001_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CROSTONNODETESTDENO001_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CROSTONNODETESTDENO001_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: ${{ github.workspace }}/Dockerfile
          registryUrl: docker.io
          registryUsername: ${{ secrets.DOCKER_USERNAME }}
          registryPassword: ${{ secrets.DOCKER_PASSWORD }}
          containerAppName: croston-nodetestdeno-001
          resourceGroup: rg-raymartf-lab
          imageToBuild: crostonj/croston-nodetestdeno-001:${{ github.sha }}


