name: Generate Swagger File

permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual trigger

jobs:
  generate-swagger:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Generate the Swagger file
      - name: Generate Swagger JSON
        run: npm run generate-swagger

      # Step 5: Commit and push the Swagger file
      - name: Commit and push Swagger file
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add swagger.json
          git commit -m "Update Swagger JSON file [skip ci]" || echo "No changes to commit"
          git push
